server:
  port: 8094

spring:
  application:
    name: messaging-microservice
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: off

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/